# This workflow checks if the selectors used to get track info still work, in
# case Spotify adjusts their DOM structure.

name: Spotify Selector Test

on:
    push:
        branches: [main]
    schedule:
        - cron: '0 */4 * * *'

jobs:
    test:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: Use Node.js 14
              uses: actions/setup-node@v1
              with:
                  node-version: 14

            - name: Install dependencies
              run: npm ci

            - name: Install xvfb
              run: sudo apt-get install xvfb

            - name: Test selectors
              run: xvfb-run --auto-servernum npm test -- __tests__/selectors.js
